# Development Override Configuration
# This file is automatically merged with docker-compose.yml when running docker compose
# Place development-specific overrides here

services:
  # Development-specific backend configuration
  backend:
    build:
      target: development
    volumes:
      - ./backend:/app:cached
      - go_modules:/go/pkg/mod:cached
      - go_cache:/root/.cache/go-build:cached
    environment:
      - GO_ENV=development
      - LOG_LEVEL=debug
      - DEBUG=true
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    command: ['air', '-c', '.air.toml']

  # Development-specific frontend configuration
  frontend:
    build:
      target: development
    volumes:
      - ./frontend:/app:cached
      - vite_cache:/app/.vite:cached
      - tanstack_cache:/app/.tanstack:cached
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # For better file watching in containers
    entrypoint: ['./start-dev.sh']

  # Development database with additional tools
  postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

# Development-specific volumes
volumes:
  postgres_data:
  postgres_logs:
  go_modules:
  go_cache:
  node_modules:
  vite_cache:
  tanstack_cache:

# Development network
networks:
  app-network:
    driver: bridge
